name: release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build_snippets_code
      - run: npm run build_snippets
      - run: npm run build_snippets_styles
      - run: npm run copy_pages

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Copy artifacts to site repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SITE_PUBLISH_PRIVATE_KEY }}

        with:
          source-directory: dist/
          target-directory: artifacts/site
          destination-github-username: john-smith-library
          destination-repository-name: john-smith-library.github.io
          user-email: <>